# Generated by Django 3.1.3 on 2020-11-27 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('accumulator_type', models.CharField(max_length=255, verbose_name='Тип аккумулятора')),
                ('ac_capacity', models.CharField(max_length=255, verbose_name='Емкость аккумулятора')),
                ('out_amperage', models.CharField(max_length=255, verbose_name='Выходное напряжение')),
                ('input_connectors', models.CharField(max_length=255, verbose_name='Входные разъемы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Earphones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('model_type', models.CharField(max_length=255, verbose_name='Тип модели')),
                ('connect_type', models.CharField(max_length=255, verbose_name='Тип подключения')),
                ('microphone', models.BooleanField(default=False, verbose_name='Наличие микрофона')),
                ('noise_suppression', models.BooleanField(default=False, verbose_name='Наличие шумоизоляции')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Время работы аккумулятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
