# Generated by Django 3.1.3 on 2020-12-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_someimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeImageModel',
        ),
    ]
